// Every name the examples import, from the header the site says it comes from. The build fails on a
// name that header does not export, so the import lines on the page are checked here.
export {
    allocBuffer,
    GEOS_finish_r,
    GEOS_init_r,
    GEOSArea_r,
    GEOSBufCapStyles,
    GEOSBuffer_r,
    GEOSBufferWithStyle_r,
    GEOSBufJoinStyles,
    GEOSDifference_r,
    GEOSDistance_r,
    GEOSFree_r,
    GEOSGeom_createLineString_r,
    GEOSGeom_destroy_r,
    GEOSGetCentroid_r,
    GEOSIntersection_r,
    GEOSisValid_r,
    GEOSisValidReason_r,
    GEOSLength_r,
    GEOSMakeValidMethods,
    GEOSMakeValidParams_create_r,
    GEOSMakeValidParams_destroy_r,
    GEOSMakeValidParams_setMethod_r,
    GEOSMakeValidWithParams_r,
    GEOSNearestPoints_r,
    GEOSNormalize_r,
    GEOSOffsetCurve_r,
    GEOSPrepare_r,
    GEOSPreparedContainsXY_r,
    GEOSPreparedGeom_destroy_r,
    GEOSPreparedIntersectsXY_r,
    GEOSPreparedRelate_r,
    GEOSUnion_r,
    GEOSversion,
    GEOSWKTReader_create_r,
    GEOSWKTReader_destroy_r,
    GEOSWKTReader_read_r,
    GEOSWKTWriter_create_r,
    GEOSWKTWriter_destroy_r,
    GEOSWKTWriter_write_r,
    readCString,
    readNumberAt,
} from '@crossbind/port-geos/geos_c.h';
