// Headers of dependencies that a build binds whole (export.bindings.headers), the way an app's
// `import * as x from '<pkg>/<header>'` would: a package that ships prebuilt bindings has no app
// importing them. An entry is a header path, or a package name standing for every header the package
// lists in export.publicHeaders.

import { releaseTargetOf } from './targets.js';

const isName = (entry) => typeof entry === 'string' && entry.length > 0;

function publicHeadersOf(packageName, dependencies) {
    const owner = dependencies.find((d) => [d.package?.name, d.general?.alias?.package].includes(packageName)
        && d.export?.publicHeaders?.length);
    if (!owner) {
        throw new Error(`crossbind: export.bindings.headers names ${packageName}, but no dependency of that name lists export.publicHeaders.`);
    }
    return owner.export.publicHeaders.map((header) => `${packageName}/${header}`);
}

function assertDistinctEntries(specifiers) {
    const owners = new Map();
    specifiers.forEach((specifier) => {
        const entry = headerEntryPath(specifier);
        if (owners.has(entry)) {
            throw new Error(`crossbind: export.bindings.headers: ${owners.get(entry)} and ${specifier} would share the entry module ${entry}.`);
        }
        owners.set(entry, specifier);
    });
    return specifiers;
}

export function boundHeaderSpecifiers({ export: exportConfig, ext, allDependencies }) {
    const entries = exportConfig.bindings?.headers ?? [];
    if (!Array.isArray(entries) || !entries.every(isName)) {
        throw new Error('crossbind: export.bindings.headers must list header paths or package names.');
    }
    const isHeader = new RegExp(`\\.(${ext.header.join('|')})$`);
    return assertDistinctEntries([...new Set(entries.flatMap((entry) => (isHeader.test(entry) ? [entry] : publicHeadersOf(entry, allDependencies))))]);
}

// The bridges come from one target's headers and macros. A linux target goes first, since every host
// builds one, so a package comes out the same on any machine.
const BRIDGE_PLATFORM_ORDER = ['linux', 'linuxmusl', 'win32', 'darwin'];
const bridgeRank = ({ platform }) => {
    const rank = BRIDGE_PLATFORM_ORDER.indexOf(platform);
    return rank < 0 ? BRIDGE_PLATFORM_ORDER.length : rank;
};
export const bridgeTargetOrder = (targets) => [...targets].sort((a, b) => bridgeRank(a) - bridgeRank(b));

// A macOS host without Docker builds no linux addon, so the targets of the runtime environment it does not
// build are candidates too: a linux package installed beside it gives the same bridges a linux build made.
export const bridgeTargets = (buildTargets, allTargets) => bridgeTargetOrder([
    ...buildTargets,
    ...allTargets.filter((target) => target.platform !== 'wasm' && !buildTargets.includes(target)
        && buildTargets.some((built) => built.runtimeEnv === target.runtimeEnv)),
]);

// A Node build reads the app's headers for the first of its own targets, in its release form, since Conan
// packages are staged for release targets only.
export const nodeBridgeTarget = (targets) => releaseTargetOf(bridgeTargetOrder(targets)[0]);

function resolveOrNull(resolve, specifier, target) {
    try {
        return resolve(specifier, target);
    } catch {
        return null;
    }
}

// A desktop build has no target that every platform package covers, so each header resolves under
// the first target whose dependency ships it.
export function resolveBoundHeaders(specifiers, targets, resolve) {
    return specifiers.map((specifier) => {
        const target = targets.find((t) => resolveOrNull(resolve, specifier, t));
        if (!target) {
            throw new Error(`crossbind: export.bindings.headers: no dependency ships ${specifier} for ${targets.map((t) => t.path).join(', ')}.`);
        }
        return { specifier, file: resolve(specifier, target), target };
    });
}

const OBJECT_LIKE_RENAME = /^\s*#\s*define\s+([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*$/gm;
const localOf = (name) => (typeof name === 'string' ? name : name.local);

// A header that renames a bound function with an object-like macro (GNU libiconv binds libiconv_open as iconv_open)
// is called by the macro's name, so the entry exports that name too.
export function headerAliases(headerText, names) {
    const bound = new Set(names.map(localOf));
    return [...headerText.matchAll(OBJECT_LIKE_RENAME)]
        .filter(([, local, wire]) => bound.has(wire) && !bound.has(local))
        .map(([, local, wire]) => ({ local, wire }));
}

export function headerEntryPath(specifier) {
    const segments = specifier.split('/');
    return segments.slice(specifier.startsWith('@') ? 2 : 1).join('/');
}

// Loading an addon is synchronous, so the entry boots it on require and an ESM import sees every
// name; initNative and AllSymbols keep the exports of the module a bundler generates for the header.
export function headerEntryModule(names, loader) {
    return [
        "'use strict';",
        '// Generated by crossbind - do not edit.',
        `const initNative = require('${loader}');`,
        'const Module = initNative.sync();',
        'exports.initNative = initNative;',
        'exports.AllSymbols = Module;',
        ...names.map((name) => (typeof name === 'string' ? { local: name, wire: name } : name))
            .map(({ local, wire }) => `exports.${local} = Module.${wire};`),
        '',
    ].join('\n');
}
