import fs from 'node:fs';
import path from 'node:path';
import { deriveLicenseExpression, formatCycloneDxSbom, formatNoticeSections } from './licenseReport.js';

export const SBOM_FILE = 'sbom.cdx.json';
const RULE = '-'.repeat(70);

export function lgplRows(rows) {
    return rows.filter((row) => /\bLGPL\b/.test(row.license ?? ''));
}

// The LLVM exception waives the notice for runtime parts compiled into a binary; every other
// component needs its text in the package.
function assertTexts(name, rows) {
    const missing = rows.filter(
        (row) => (!row.licenseText || row.licenseText.includes('(missing:')) && !/\bLLVM-exception\b/.test(row.license ?? ''),
    );
    if (missing.length) {
        throw new Error(
            `${name}: no license text for ${missing.map((row) => row.name).join(', ')}; build the package so crossbind licenses can read it.`,
        );
    }
}

const listOf = (names) => (names.length > 1 ? `${names.slice(0, -1).join(', ')} and ${names.at(-1)}` : names[0]);

function relinkSection({ name, version, repository, projectPath, addonFile, rows }) {
    const tag = `${name}@${version}`;
    const repo = repository.replace(/\.git$/, '');
    return [
        '## Relinking the LGPL libraries',
        '',
        `This addon links ${listOf(rows.map((row) => row.name))} statically; their sections below give their licenses.`,
        'You may replace them with modified versions and relink the addon:',
        '',
        `1. Get the corresponding source. This package was built from ${repo} at the tag ${tag}:`,
        `   ${repo}/tree/${tag}`,
        '   The upstream sources are the tarballs the sections below list, with their SHA-256.',
        `2. In ${projectPath}, point the library at your modified source with a crossbind.overrides.js file`,
        '   (docs/playbooks/override-dependencies.md in that repository).',
        `3. Build the addon with \`pnpm install\` and \`pnpm --dir ${projectPath} build\`. Linux and Windows`,
        '   addons build in Docker, macOS addons on a Mac.',
        `4. The build writes ${addonFile} in ${projectPath}; it replaces the file of that name in this package.`,
    ].join('\n');
}

export function nodePackageLicense({ name, version, repository, projectPath, addonFile = null, rows }) {
    assertTexts(name, rows);
    const expression = deriveLicenseExpression(rows);
    const relinked = addonFile ? lgplRows(rows) : [];
    const lines = [
        addonFile
            ? `${name} ships a Node-API addon that links the components below statically.`
            : `${name} ships the JavaScript bindings, types and data of the components below; the addons that link them are in its platform packages.`,
        'The full license text of every component follows.',
        '',
        'Effective license expression (also package.json "license"):',
        '',
        `    ${expression}`,
        '',
        `The machine-readable component inventory is ${SBOM_FILE} next to this file.`,
        '',
        'GENERATED by `crossbind licenses --package` - do not edit. This file states facts and is not legal',
        'advice; the compliance assessment is yours.',
        '',
        RULE,
        '',
        ...(relinked.length ? [relinkSection({ name, version, repository, projectPath, addonFile, rows: relinked }), '', RULE, ''] : []),
        formatNoticeSections(rows).join('\n\n'),
        '',
    ];
    return { expression, text: lines.join('\n') };
}

export function setManifestLicense(dir, expression) {
    const file = path.join(dir, 'package.json');
    const manifest = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (manifest.license === expression) return;
    fs.writeFileSync(file, `${JSON.stringify({ ...manifest, license: expression }, null, 4)}\n`);
}

export function writeNodePackageLicense(dir, meta) {
    const { expression, text } = nodePackageLicense(meta);
    fs.writeFileSync(path.join(dir, 'LICENSE'), text);
    fs.writeFileSync(path.join(dir, SBOM_FILE), formatCycloneDxSbom(meta.rows, { name: meta.name, version: meta.version }));
    setManifestLicense(dir, expression);
    return expression;
}

// What a Node-API package's license names, from its manifest and its place in the repository it builds
// from: an addon package's is the addon its own build writes.
export function nodePackageMeta({ package: manifest = {}, paths }) {
    const repository = typeof manifest.repository === 'string' ? manifest.repository : (manifest.repository?.url ?? '');
    return {
        name: manifest.name,
        version: manifest.version,
        repository,
        projectPath: path.relative(paths.base, paths.project).split(path.sep).join('/') || '.',
        addonFile: manifest.os && /\.node$/.test(manifest.main ?? '') ? manifest.main : null,
    };
}
