import { execFileSync } from 'node:child_process';
import { getContentHash } from './hash.js';

// Digest-pinned so a re-pushed tag can't swap the compiler; IMAGE_VERSION only names containers
// and records which release these digests came from - bump every pin via scripts/pin-docker-image.js.
const REGISTRY = 'ghcr.io/crossbind';
const IMAGE_VERSION = '1.0.2';

// One entry per role in the image family. `ref` is the multi-arch index, which a native pull
// resolves per platform; `amd64` is that index's linux/amd64 leaf, needed wherever the CLI forces
// a platform, because the classic image store holds one platform per digest reference. The android
// image is amd64-only - Google ships the linux NDK host tools for x86_64 alone - so its index
// carries a single leaf and both of its refs resolve to the same platform.
// Generated by scripts/pin-docker-image.js from a release digest table; do not edit by hand.
const IMAGES = {
    web: {
        ref: `${REGISTRY}/web@sha256:c1d1d81a4775871cd90c8ac980e0a5f87cb7890822117f77be1c8345f51b1f47`,
        amd64: `${REGISTRY}/web@sha256:9010948430c95120b8c19f73377f8684bc6b54e03537790f465237225e48dae2`,
    },
    android: {
        ref: `${REGISTRY}/android@sha256:a3facbf2181f568f12a9fe89054188895665a63e2c147b790fd7e25f3e128ac8`,
        amd64: `${REGISTRY}/android@sha256:4694c6210379a87d8cf0e7f8b56a76a9c74a8724a1aff037c943dcdb521f4de1`,
    },
};

const OVERRIDE_KEYS = { web: 'CROSSBIND_IMAGE_WEB', android: 'CROSSBIND_IMAGE_ANDROID' };

// Which image a target compiles in: wasm and wasi share the web image, ios never reaches docker.
export function imageRoleFor(target) {
    return target?.platform === 'android' ? 'android' : 'web';
}

const warned = new Set();
function warnOnce(message) {
    if (warned.has(message)) return;
    warned.add(message);
    console.warn(message);
}

// An override is one of three distinct situations, and only the first keeps the reproducibility
// guarantee: same digest from another registry, a digest the release does not ship, or a bare tag.
function resolveRef(role, expected) {
    const key = OVERRIDE_KEYS[role];
    const explicit = process.env[key];
    if (explicit) {
        if (explicit !== expected) {
            warnOnce(explicit.includes('@sha256:')
                ? `crossbind: unsupported toolchain override - ${key} pins a digest the release does not ship (${explicit}).`
                : `crossbind: mutable override - ${key} names the tag ${explicit}; the reproducibility guarantee is disabled.`);
        }
        return explicit;
    }

    const mirror = process.env.CROSSBIND_REGISTRY_MIRROR;
    const at = expected.indexOf('@');
    if (mirror && at !== -1) {
        warnOnce(`crossbind: pulling from the registry mirror ${mirror} (same digest as the release).`);
        return `${mirror.replace(/\/+$/, '')}/${expected.slice(0, at).split('/').pop()}${expected.slice(at)}`;
    }
    return expected;
}

export function getDockerImage(role = 'web', platform) {
    const image = IMAGES[role];
    if (!image) throw new Error(`crossbind: unknown docker image role "${role}".`);
    return resolveRef(role, platform === 'linux/amd64' ? image.amd64 : image.ref);
}

// One container per image: a web container carries no NDK, and android runs a forced platform.
// The version is part of the name so an image bump cannot silently reuse a container built from
// the previous toolchain.
export function getDockerContainerName(base, role = 'web') {
    return `crossbind-${IMAGE_VERSION}-${role}-${getContentHash(base)}`.replaceAll('/', '-').replaceAll(':', '-');
}

const pulledRefs = new Set();

// `docker images -q` can't resolve digest refs; `inspect` handles both.
function isImagePresent(ref) {
    try {
        execFileSync('docker', ['image', 'inspect', ref], { stdio: 'ignore' });
        return true;
    } catch {
        return false;
    }
}

export default function pullDockerImage(role = 'web', platform) {
    const ref = getDockerImage(role, platform);
    if (pulledRefs.has(ref)) return;

    if (!isImagePresent(ref)) {
        console.log('');
        console.log('===========================================================');
        console.log('============= Downloading the docker image... =============');
        console.log('===========================================================');
        console.log('');
        execFileSync('docker', ['pull', ref], { stdio: 'inherit' });
        console.log('');
        console.log('===========================================================');
        console.log('');
    }

    pulledRefs.add(ref);
}
