// The one module a package publishes per runtime binary, dist/<runtimeEnv>/<format>.mjs. It exports every
// bound name as an ESM live binding that initNative() fills, the way a bundler's module for a header does,
// so `import { initNative, X } from '<package>/node/napi'` works with or without init options.

const PROXY_NAMES = new Set(['initNative', 'AllSymbols']);

// A name is a plain string or { local, wire }: the second exports `local` while reading the differently
// registered `wire` off the module. Two headers may bind one name; the module exports it once.
export function uniqueBindings(names) {
    const seen = new Set();
    return names
        .map((name) => (typeof name === 'string' ? { local: name, wire: name } : name))
        .filter(({ local }) => {
            if (PROXY_NAMES.has(local) || seen.has(local)) return false;
            seen.add(local);
            return true;
        });
}

// Each runtime's loader, imported as `boot`, and the config it boots with; the binaries sit in dist, one
// directory above the entry.
export const ENTRY_RUNTIMES = {
    // The Node-API loader and the Node wasm build are both CommonJS.
    node: (loader) => ({
        imports: ["import { createRequire } from 'node:module';", `const boot = createRequire(import.meta.url)('../${loader}');`],
        config: 'config',
    }),
    // Edge runtimes cannot compile WebAssembly from bytes, so the binary is a module import their bundler resolves.
    edge: (loader, wasm) => ({
        imports: [`import boot from '../${loader}';`, `import wasm from '../${wasm}';`],
        config: '{ getWasmFunction: () => wasm, ...config }',
    }),
};

// A bound name may be a JavaScript reserved word, which an export list accepts but a declaration does not.
export function runtimeEntryModule(names, { imports, config }) {
    const bindings = uniqueBindings(names);
    return [
        '// Generated by crossbind - do not edit.',
        ...imports,
        '',
        'export let AllSymbols = {};',
        ...bindings.map(({ local }) => `let $${local} = null;`),
        ...(bindings.length ? [`export { ${bindings.map(({ local }) => `$${local} as ${local}`).join(', ')} };`] : []),
        '',
        'export function initNative(config = {}) {',
        `    return boot(${config}).then((m) => {`,
        '        AllSymbols = m;',
        ...bindings.map(({ local, wire }) => `        $${local} = m.${wire};`),
        '        return m;',
        '    });',
        '}',
        'initNative.terminate = () => boot.terminate();',
        '',
    ].join('\n');
}
