// Generated by scripts/pin-rust-sysroot.js - do not edit by hand.
//
// The published sysroot image a host build (RUNNER=LOCAL) reads its Rust sysroots out of - the same
// object the web image embeds, not a repackaged copy, so the two channels cannot drift. The index
// digest is the whole contract: the loader verifies the index body against it, then each descriptor
// inside a verified body authenticates the next fetch, down to the layer.
export default {
    version: '1.0.2',
    image: 'ghcr.io/crossbind/rust-sysroot',
    index: 'sha256:0ab2e522b1b09b2af7f312d4b940ab92ee470e8165df4b563e274a4eb2fdb903',
};
