// Generated by scripts/pin-rust-sysroot.js - do not edit by hand.
//
// The Rust sysroot artifact a host build (RUNNER=LOCAL) downloads instead of rebuilding std the
// nightly way. null until the archive is attached to a release: mt then keeps the -Zbuild-std
// path, which works, just slower and on nightly.
export default null;
