// Every name the examples import, from the header the site says it comes from. The build fails on a
// name that header does not export, so the import lines on the page are checked here.
export {
    GTIFDirectoryInfo,
    GTIFFree,
    GTIFImageToPCS,
    GTIFImport,
    GTIFKeyCode,
    GTIFKeyGetASCII,
    GTIFKeyGetSHORT,
    GTIFKeyInfo,
    GTIFNewSimpleTags,
    GTIFPCSToImage,
    GTIFTypeName,
    GTIFValueNameEx,
    allocBuffer,
    allocPointer,
    readCString,
    readNumberAt,
    readPointerAt,
    releaseCallback,
    writeBytes,
    writeNumberAt,
} from '@crossbind/port-geotiff/geotiff.h';
export {
    GTIFAllocDefn,
    GTIFFreeDefn,
    GTIFFreeMemory,
    GTIFGetDatumInfo,
    GTIFGetDefn,
    GTIFGetEllipsoidInfo,
    GTIFGetGCSInfo,
    GTIFGetPCSInfo,
    GTIFGetPMInfo,
    GTIFGetProj4Defn,
    GTIFGetProjTRFInfo,
    GTIFGetUOMLengthInfo,
    GTIFProj4FromLatLong,
    GTIFProj4ToLatLong,
} from '@crossbind/port-geotiff/geo_normalize.h';
