// App-local Rust surface: src/index.mjs imports it like a header, and the build links its bridge
// crate into the addon - no package needed.
pub struct Counter {
    total: i32,
}

impl Counter {
    pub fn new(start: i32) -> Self {
        Counter { total: start }
    }
    pub fn add(&mut self, n: i32) -> i32 {
        self.total += n;
        self.total
    }
    // &self on purpose: exercises the generated by-ref shim.
    pub fn total(&self) -> i32 {
        self.total
    }
}
