import { describe, test, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
    lgplRows, nodePackageLicense, nodePackageMeta, setManifestLicense, writeNodePackageLicense,
} from '../src/utils/packageLicense.js';

const row = (name, license, extra = {}) => ({
    name,
    license,
    licenseText: `${name} license text`,
    sourceUrl: `https://example.org/${name}.tar.gz`,
    sha256: 'a'.repeat(64),
    ...extra,
});
const gdalRows = [
    row('gdal', 'MIT'),
    row('geos', 'LGPL-2.1-only'),
    row('iconv', 'LGPL-2.1-or-later'),
    row('spatialite', 'MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later'),
    row('zstd', 'BSD-3-Clause OR GPL-2.0-only'),
    row('llvm-runtimes', 'Apache-2.0 WITH LLVM-exception', { licenseText: null }),
];
const addon = {
    name: '@crossbind/port-gdal-standalone-napi-linux-x64',
    version: '2.0.0-beta.63',
    repository: 'https://github.com/crossbind/crossbind.git',
    projectPath: 'ports/gdal/standalone-napi-linux-x64',
    addonFile: 'dist/gdal-standalone-napi.linux-x64.node',
};

let work;

beforeEach(() => {
    work = fs.mkdtempSync(path.join(os.tmpdir(), 'crossbind-package-license-'));
});

afterEach(() => {
    fs.rmSync(work, { recursive: true, force: true });
});

describe('nodePackageLicense', () => {
    test('the LGPL rows are the libraries the LGPL may cover, not every copyleft alternative', () => {
        expect(lgplRows(gdalRows).map((entry) => entry.name)).toEqual(['geos', 'iconv', 'spatialite']);
    });

    test('an addon linking LGPL libraries carries the source tag and the steps to relink it in its own package', () => {
        const { expression, text } = nodePackageLicense({ ...addon, rows: gdalRows });

        expect(text).toMatch(/^@crossbind\/port-gdal-standalone-napi-linux-x64 ships a Node-API addon/);
        expect(text).toContain(`    ${expression}\n`);
        expect(expression).toMatch(/\bLGPL-2\.1-only\b/);
        expect(text).toContain('geos, iconv and spatialite');
        expect(text).toContain('https://github.com/crossbind/crossbind/tree/@crossbind/port-gdal-standalone-napi-linux-x64@2.0.0-beta.63');
        expect(text).toContain('crossbind.overrides.js');
        expect(text).toContain('pnpm --dir ports/gdal/standalone-napi-linux-x64 build');
        expect(text).toContain('The build writes dist/gdal-standalone-napi.linux-x64.node in ports/gdal/standalone-napi-linux-x64');
        expect(text).toContain('GENERATED by `crossbind licenses --package`');
        gdalRows.forEach((entry) => expect(text).toContain(`## ${entry.name} — ${entry.license}`));
        expect(text.indexOf('Relinking')).toBeLessThan(text.indexOf('## gdal'));
    });

    test('an addon without LGPL libraries and the package of the bindings carry no relink steps', () => {
        const permissive = [row('zlib', 'Zlib'), row('crossbind', 'MIT')];

        expect(nodePackageLicense({ ...addon, rows: permissive }).text).not.toMatch(/Relinking/);
        const bindings = nodePackageLicense({ ...addon, name: '@crossbind/port-gdal-standalone-napi', addonFile: null, rows: gdalRows });
        expect(bindings.text).not.toMatch(/Relinking/);
        expect(bindings.text).toMatch(/^@crossbind\/port-gdal-standalone-napi ships the JavaScript bindings/);
    });

    test('refuses a component whose text is missing, except a runtime its exception covers', () => {
        const missing = [row('giflib', 'MIT', { licenseText: '=== COPYING ===\n\n(missing: build the package once)' })];

        expect(() => nodePackageLicense({ ...addon, rows: missing })).toThrow(/giflib/);
        expect(() => nodePackageLicense({ ...addon, rows: [row('mingw-w64-runtime', 'LicenseRef-MinGW-w64-runtime', { licenseText: null })] }))
            .toThrow(/mingw-w64-runtime/);
        expect(() => nodePackageLicense({ ...addon, rows: [row('llvm-runtimes', 'Apache-2.0 WITH LLVM-exception', { licenseText: null })] }))
            .not.toThrow();
    });
});

describe('writeNodePackageLicense', () => {
    test('writes LICENSE, the SBOM and the derived license field of a package', () => {
        fs.writeFileSync(path.join(work, 'package.json'), `${JSON.stringify({ name: addon.name, version: addon.version, license: 'MIT', os: ['linux'] }, null, 4)}\n`);

        const expression = writeNodePackageLicense(work, { ...addon, rows: gdalRows });

        const manifest = JSON.parse(fs.readFileSync(path.join(work, 'package.json'), 'utf8'));
        expect(manifest.license).toBe(expression);
        expect(Object.keys(manifest)).toEqual(['name', 'version', 'license', 'os']);
        expect(fs.readFileSync(path.join(work, 'LICENSE'), 'utf8')).toContain(expression);
        const sbom = JSON.parse(fs.readFileSync(path.join(work, 'sbom.cdx.json'), 'utf8'));
        expect(sbom.metadata.component.name).toBe(addon.name);
        expect(sbom.components.map((component) => component.name).sort()).toEqual(gdalRows.map((entry) => entry.name).sort());
    });

    test('leaves package.json untouched when its license is already the derived one', () => {
        const file = path.join(work, 'package.json');
        fs.writeFileSync(file, '{"name":"x","license":"MIT AND Zlib"}');

        setManifestLicense(work, 'MIT AND Zlib');

        expect(fs.readFileSync(file, 'utf8')).toBe('{"name":"x","license":"MIT AND Zlib"}');
    });
});

describe('nodePackageMeta', () => {
    const paths = { base: '/repo', project: '/repo/ports/gdal/standalone-napi-linux-x64' };

    test('names the addon an addon package\'s own build writes', () => {
        const manifest = {
            name: addon.name, version: addon.version, repository: addon.repository, os: ['linux'], main: 'dist/gdal-standalone-napi.linux-x64.node',
        };

        expect(nodePackageMeta({ package: manifest, paths })).toEqual({
            name: addon.name, version: addon.version, repository: addon.repository, projectPath: addon.projectPath, addonFile: addon.addonFile,
        });
    });

    test('names no addon for the package of the bindings, and reads a repository object', () => {
        const manifest = { name: '@crossbind/port-gdal-standalone-napi', version: addon.version, repository: { type: 'git', url: addon.repository } };

        expect(nodePackageMeta({ package: manifest, paths: { base: '/repo', project: '/repo/ports/gdal/standalone-napi' } }))
            .toMatchObject({ repository: addon.repository, projectPath: 'ports/gdal/standalone-napi', addonFile: null });
    });
});
