import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import pullDockerImage, { getDockerImage } from '../utils/pullDockerImage.js';
import { DOCKER_RUN_SECURITY_ARGS } from '../utils/dockerSecurity.js';
import { remoteVariables } from '../utils/remoteRunner.js';

// `crossbind runner`: a runner is the toolchain image this CLI pins plus the server in src/runner, which
// reaches the image mounted (start) or copied by a generated Dockerfile (init); no runner image is published.

export const RUNNER_ROLES = ['web', 'android', 'linux', 'windows'];
const RUNNER_PORT = 8787;
const RUNNER_SOURCE = fileURLToPath(new URL('../runner', import.meta.url));
const CONTAINER_RUNNER = '/opt/crossbind/runner';
const TOKEN_BYTES = 24;
const VERSION = JSON.parse(fs.readFileSync(new URL('../../package.json', import.meta.url), 'utf8')).version;

const runnerName = (role) => `crossbind-runner-${role}`;
// Google ships the linux NDK for x86_64 only, so an android runner is always amd64.
const platformOf = (role) => (role === 'android' ? 'linux/amd64' : undefined);
const runnerImage = (role) => getDockerImage(role, platformOf(role));

export const newRunnerToken = () => crypto.randomBytes(TOKEN_BYTES).toString('base64url');

// Each image has its own host port, so the runners one build needs can share a machine.
export const runnerHostPort = (role) => RUNNER_PORT + RUNNER_ROLES.indexOf(role);

export function runnerEnv(role, url, token) {
    const variables = remoteVariables(role);
    return `${variables.url}=${url} ${variables.token}=${token}`;
}

function assertRole(role) {
    if (!RUNNER_ROLES.includes(role)) throw new Error(`crossbind: unknown image "${role}" - expected one of ${RUNNER_ROLES.join(', ')}.`);
}

export function runnerStartArgs({ role, port, host }) {
    const platform = platformOf(role);
    return [
        'run', '-d', '--name', runnerName(role), '--restart', 'unless-stopped',
        ...(platform ? ['--platform', platform] : []),
        ...DOCKER_RUN_SECURITY_ARGS,
        '-p', `${host}:${port}:${RUNNER_PORT}`,
        '-v', `${RUNNER_SOURCE}:${CONTAINER_RUNNER}:ro`,
        // By name only: docker reads the value from its own environment, so the token stays off the command line.
        '-e', 'CROSSBIND_RUNNER_TOKEN',
        '-e', `CROSSBIND_RUNNER_IMAGE=${runnerImage(role)}`,
        '-e', `CROSSBIND_RUNNER_ROLE=${role}`,
        '--entrypoint', 'node',
        runnerImage(role),
        `${CONTAINER_RUNNER}/server.js`,
    ];
}

export function startRunner({ role = 'web', port = runnerHostPort(role), host = '127.0.0.1', token } = {}) {
    assertRole(role);
    const secret = token || process.env.CROSSBIND_RUNNER_TOKEN || newRunnerToken();
    pullDockerImage(role, platformOf(role));
    execFileSync('docker', runnerStartArgs({ role, port, host }), {
        stdio: ['ignore', 'ignore', 'inherit'],
        env: { ...process.env, CROSSBIND_RUNNER_TOKEN: secret },
    });
    return { name: runnerName(role), url: `http://${host}:${port}`, token: secret };
}

export function stopRunner({ role = 'web' } = {}) {
    assertRole(role);
    execFileSync('docker', ['rm', '-f', runnerName(role)], { stdio: 'inherit' });
}

function dockerfile(role) {
    const platform = platformOf(role);
    return [
        `# Generated by crossbind ${VERSION}: the ${role} toolchain image this CLI pins, plus its runner.`,
        `FROM ${platform ? `--platform=${platform} ` : ''}${runnerImage(role)}`,
        `COPY runner ${CONTAINER_RUNNER}`,
        `ENV CROSSBIND_RUNNER_IMAGE=${runnerImage(role)} CROSSBIND_RUNNER_ROLE=${role}`,
        `EXPOSE ${RUNNER_PORT}`,
        `ENTRYPOINT ["node", "${CONTAINER_RUNNER}/server.js"]`,
        '',
    ].join('\n');
}

// One machine: a runner keeps its build tree on its own disk, so a second machine would hold another tree.
function flyToml(role) {
    return [
        `# Generated by crossbind ${VERSION}. Create the app with \`fly launch --copy-config --no-deploy --ha=false\`,`,
        '# set its token with `fly secrets set CROSSBIND_RUNNER_TOKEN=<token>`, then run `fly deploy --ha=false`.',
        `app = "crossbind-runner-${role}"`,
        '',
        '[build]',
        '  dockerfile = "Dockerfile"',
        '',
        '[http_service]',
        `  internal_port = ${RUNNER_PORT}`,
        '  force_https = true',
        '  auto_stop_machines = "stop"',
        '  auto_start_machines = true',
        '  min_machines_running = 0',
        '',
        '[[vm]]',
        '  size = "performance-4x"',
        '  memory = "16gb"',
        '',
    ].join('\n');
}

// Cloudflare's GA scheduling (`default` policy), driven through the Durable Object container API, so the
// folder needs no npm dependency. One container: a runner keeps one build tree.
function wranglerConfig(role) {
    return [
        `// Generated by crossbind ${VERSION}. \`npx wrangler deploy\` builds the image with the local Docker, then`,
        '// `npx wrangler secret put CROSSBIND_RUNNER_TOKEN` sets the token builds must send.',
        '{',
        `    "name": "crossbind-runner-${role}",`,
        '    "main": "src/worker.js",',
        '    "compatibility_date": "2026-09-01",',
        '    "containers": [',
        '        {',
        '            "class_name": "CrossbindRunner",',
        '            "image": "./Dockerfile",',
        '            "instance_type": "standard-4",',
        '            "max_instances": 1',
        '        }',
        '    ],',
        '    "durable_objects": {',
        '        "bindings": [{ "name": "RUNNER", "class_name": "CrossbindRunner" }]',
        '    },',
        '    "exports": {',
        '        "CrossbindRunner": { "type": "durable-object", "storage": "sqlite" }',
        '    }',
        '}',
        '',
    ].join('\n');
}

function cloudflareWorker(role) {
    return [
        `// Generated by crossbind ${VERSION}: a Worker in front of one ${role} runner container.`,
        "import { DurableObject } from 'cloudflare:workers';",
        '',
        `const RUNNER_PORT = ${RUNNER_PORT};`,
        'const READY_ATTEMPTS = 100;',
        'const READY_WAIT_MS = 200;',
        '',
        'const wait = (ms) => new Promise((resolve) => { setTimeout(resolve, ms); });',
        '',
        'export class CrossbindRunner extends DurableObject {',
        '    async fetch(request) {',
        '        if (!this.ctx.container.running) this.ready = null;',
        '        this.ready ??= this.start().catch((error) => {',
        '            this.ready = null;',
        '            throw error;',
        '        });',
        '        await this.ready;',
        '        return this.ctx.container.getTcpPort(RUNNER_PORT).fetch(request);',
        '    }',
        '',
        '    async start() {',
        '        // Builds fetch crates, conan packages and library sources, so the container reaches the internet.',
        '        if (!this.ctx.container.running) {',
        '            this.ctx.container.start({ enableInternet: true, env: { CROSSBIND_RUNNER_TOKEN: this.env.CROSSBIND_RUNNER_TOKEN } });',
        '        }',
        '        const port = this.ctx.container.getTcpPort(RUNNER_PORT);',
        '        for (let attempt = 0; attempt < READY_ATTEMPTS; attempt += 1) {',
        '            try {',
        "                if ((await port.fetch('http://runner/v1/health')).ok) return;",
        '            } catch {',
        '                // The runner inside is still starting.',
        '            }',
        '            await wait(READY_WAIT_MS);',
        '        }',
        "        throw new Error('crossbind runner: the container did not start');",
        '    }',
        '}',
        '',
        'export default {',
        '    async fetch(request, env) {',
        '        // The runner checks the token too; checking it here keeps a stranger from waking the container.',
        "        if (!env.CROSSBIND_RUNNER_TOKEN || request.headers.get('authorization') !== 'Bearer ' + env.CROSSBIND_RUNNER_TOKEN) {",
        "            return Response.json({ error: 'invalid token' }, { status: 401 });",
        '        }',
        "        return env.RUNNER.getByName('runner').fetch(request);",
        '    },',
        '};',
        '',
    ].join('\n');
}

const PLATFORMS = {
    cloudflare: {
        files: (role) => ({ 'wrangler.jsonc': wranglerConfig(role), 'src/worker.js': cloudflareWorker(role) }),
        steps: (dir, token, role) => [
            `cd ${dir}`,
            'npx wrangler deploy   (Docker must be running: wrangler builds the image locally)',
            `npx wrangler secret put CROSSBIND_RUNNER_TOKEN   (paste ${token})`,
            `then build with ${runnerEnv(role, `https://crossbind-runner-${role}.<account>.workers.dev`, token)}`,
        ],
    },
    fly: {
        files: (role) => ({ 'fly.toml': flyToml(role) }),
        steps: (dir, token, role) => [
            `cd ${dir}`,
            'fly launch --copy-config --no-deploy --ha=false',
            `fly secrets set CROSSBIND_RUNNER_TOKEN=${token}`,
            'fly deploy --ha=false',
            `then build with ${runnerEnv(role, 'https://<app>.fly.dev', token)}`,
        ],
    },
};

export const RUNNER_PLATFORMS = Object.keys(PLATFORMS);

export const deploySteps = (platform, dir, token, role) => PLATFORMS[platform].steps(dir, token, role);

export function initRunner({ platform, role = 'web', dir }) {
    assertRole(role);
    if (!PLATFORMS[platform]) throw new Error(`crossbind: runner init knows ${RUNNER_PLATFORMS.join(', ')}, not ${platform}.`);
    if (fs.existsSync(dir) && fs.readdirSync(dir).length > 0) throw new Error(`crossbind: ${dir} is not empty; runner init writes a fresh folder.`);
    fs.mkdirSync(path.join(dir, 'runner'), { recursive: true });
    fs.readdirSync(RUNNER_SOURCE).filter((file) => file.endsWith('.js'))
        .forEach((file) => fs.copyFileSync(path.join(RUNNER_SOURCE, file), path.join(dir, 'runner', file)));
    Object.entries({ Dockerfile: dockerfile(role), ...PLATFORMS[platform].files(role) }).forEach(([name, text]) => {
        fs.mkdirSync(path.dirname(path.join(dir, name)), { recursive: true });
        fs.writeFileSync(path.join(dir, name), text);
    });
    return { dir };
}
