import fs from 'node:fs';
import upath from 'upath';
import loadJson from '../utils/loadJson.js';
import writeIfChanged from '../utils/writeIfChanged.js';
import { parseCppSurface, emitCppDts } from '../utils/cppDts.js';
import { headerAliases } from '../utils/boundHeaders.js';
import { runtimeEntryModule, uniqueBindings } from '../utils/runtimeEntries.js';

function namesOf({ file, bridge, names: rustNames }) {
    if (rustNames) return rustNames;
    const names = loadJson(`${bridge}.exports.json`);
    if (!names) throw new Error(`crossbind: ${file} left no export list beside its bridge (${bridge}.exports.json).`);
    return [...names, ...headerAliases(fs.readFileSync(file, 'utf8'), names)];
}

function surfaceOf(headers) {
    const classes = new Map();
    headers.filter(({ file, names }) => !names && !file.endsWith('.i')).forEach(({ file }) => {
        parseCppSurface(fs.readFileSync(file, 'utf8'), () => {}).classes
            .forEach((cls) => { if (!classes.has(cls.name)) classes.set(cls.name, cls); });
    });
    return { classes: [...classes.values()] };
}

// A Rust import's names go out under the names they are registered by: two crates may both export `Version`, and
// the import hooks give each crate's import its own.
const registeredNamesOf = (header) => (header.names ? header.names.map((name) => (typeof name === 'string' ? name : name.wire)) : namesOf(header));

// Writes the entry module of one runtime binary and its declarations, from the headers bound into it,
// each { file, bridge }, and the Rust imports linked into it, each { file, names }.
export default function writeRuntimeEntry(entry, headers, runtime) {
    const names = headers.flatMap(registeredNamesOf);
    writeIfChanged(entry, runtimeEntryModule(names, runtime));
    writeIfChanged(entry.replace(/\.mjs$/, '.d.mts'), emitCppDts(surfaceOf(headers), uniqueBindings(names).map(({ local }) => local), 'sync'));
}

const IMPORT_HOOKS = new URL('../assets/node-import-hooks.mjs', import.meta.url);

// The module `node --import` loads ahead of the app, so the app imports the bound headers themselves: each
// header by its real path, with the bare specifiers that name it (imports, from findAppNativeImports) and its
// names, each with the entry's name for it where the two differ.
export function writeImportHooks(entry, headers, imports, extensions) {
    // Node runs the register file from its real path, so the files it names are relative to that.
    const dir = upath.normalize(fs.realpathSync(upath.dirname(entry)));
    const natives = headers.map((header) => {
        const file = upath.normalize(fs.realpathSync(header.file));
        return {
            file: upath.relative(dir, file),
            specifiers: imports.get(file)?.specifiers ?? [],
            names: uniqueBindings(namesOf(header)).map(({ local, wire }) => (local === wire ? local : { local, wire })),
        };
    });
    writeIfChanged(`${dir}/hooks.mjs`, fs.readFileSync(IMPORT_HOOKS, 'utf8'));
    writeIfChanged(entry.replace(/\.mjs$/, '.register.mjs'), [
        '// Generated by crossbind - do not edit.',
        "import registerNativeImports from './hooks.mjs';",
        '',
        `registerNativeImports(new URL('./${upath.basename(entry)}', import.meta.url), ${JSON.stringify({ extensions, natives }, null, 4)});`,
        '',
    ].join('\n'));
}

// Once the sources import nothing native, no start loads hooks an earlier build left; hooks.mjs stays while the other
// binary's hooks still import it.
export function removeImportHooks(entry) {
    const dir = upath.dirname(entry);
    fs.rmSync(entry.replace(/\.mjs$/, '.register.mjs'), { force: true });
    if (fs.existsSync(dir) && !fs.readdirSync(dir).some((file) => file.endsWith('.register.mjs'))) fs.rmSync(`${dir}/hooks.mjs`, { force: true });
}
