// Every name the examples import, from the header the site says it comes from. The build fails on a
// name that header does not export, so the import lines on the page are checked here. A helper that
// both headers export is re-exported from geodesic.h under an alias: a module exports a name once. The
// page's own calls through the module are here too: a header binds only the functions an import names.
export {
    allocBuffer,
    allocPointer,
    PJ_DIRECTION,
    PJ_PROJ_STRING_TYPE,
    PJ_TYPE,
    PJ_WKT_TYPE,
    proj_as_proj_string,
    proj_as_projjson,
    proj_as_wkt,
    proj_context_create,
    proj_context_destroy,
    proj_context_errno,
    proj_context_errno_string,
    proj_create,
    proj_create_crs_to_crs,
    proj_create_from_name,
    proj_crs_get_coordinate_system,
    proj_cs_get_axis_count,
    proj_cs_get_axis_info,
    proj_destroy,
    proj_errno,
    proj_get_area_of_use,
    proj_get_id_auth_name,
    proj_get_id_code,
    proj_get_name,
    proj_identify,
    proj_info,
    proj_int_list_destroy,
    proj_is_deprecated,
    proj_list_destroy,
    proj_list_get,
    proj_list_get_count,
    proj_normalize_for_visualization,
    proj_trans_generic,
    readCString,
    readNumberAt,
    readPointerAt,
    writeNumberAt,
} from '@crossbind/port-proj/proj.h';
export {
    allocBuffer as geodesicAllocBuffer,
    geod_direct,
    geod_geodesic,
    geod_init,
    geod_inverse,
    geod_polygonarea,
    readNumberAt as geodesicReadNumberAt,
    writeNumberAt as geodesicWriteNumberAt,
} from '@crossbind/port-proj/geodesic.h';
